;;; funkwha.el --- Description -*- lexical-binding: t; -*-
;;
;; Copyright (C) 2021 critbase
;;
;; Author: critbase <critbased@gmail.com>
;; Maintainer: critbase <critbased@gmail.com>
;; Created: February 16, 2021
;; Modified: February 16, 2021
;; Version: 0.0.1
;; Keywords: music
;; Homepage: https://gitlab.com/critbase/funkwha.el
;; Package-Requires: ((emacs "24.3"))
;;
;; This file is not part of GNU Emacs.
;;
;;; Commentary:
;;
;;  Description
;;
;;; Code:

;; * Dependencies

(require 'url)
(require 'json)

;; * Customizable Global variables
(defcustom funkwha-host "https://open.audio"
  "Hostname of your funkwhale instance as a string. Shouldn't be nil."
  :type 'string
  :group 'funkwha)

(defcustom funkwha-token ""
  "Access token generated by Funkwhale.
You can get one for your instance by creating an application and copying the access token."
  :type 'string
  :group 'funkwha)

(defun funkwha-list-tracks ()
  "List."
  (let ((url-request-method "GET")
        (url-request-extra-headers (list (cons "Authorization" (concat "Bearer " funkwha-token)))))
    (with-current-buffer (url-retrieve-synchronously (concat funkwha-host "/api/v1/tracks"))
      ;(buffer-string)
      (goto-char url-http-end-of-headers)
      (json-read)
      )))

(defvar funkwha-tracks
  (funkwha-list-tracks))

(provide 'funkwha)
;;; funkwha.el ends here
